apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'projeto-final'
        static_configs:
          - targets: ['projeto-final:8080']
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: http
        metrics_path: /metrics/cadvisor
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:80
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: node
            replacement: $1
