name: Deploy no Minikube

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clonar o código
        uses: actions/checkout@v3

      - name: Verificar acesso ao cluster
        run: kubectl cluster-info

      - name: Aplicar manifests
        run: kubectl apply -f kubernetes/
